config/routes.rb
Rails.application.routes.draw do
  resources :file_upload_questions
  resources :results
  resources :questions
  get 'select_quiz_type', to: 'questions#select_quiz_type'
  get 'quiz_questions',to: 'questions#quiz_questions'
  resources :quizzes
  resources :subjects
  post 'upload_question', to: 'questions#upload_question'

  # resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    post 'sign_up_with_credentials',to: 'admins/sessions#sign_up_with_credentials'
    post 'sign_in_with_credentials', to: 'admins/sessions#sign_in_with_credentials'
    post 'register', to: 'admins/sessions#register'
  end


  post 'test_result',to: 'questions#test_result'
  post 'upload_question',to: 'questions#upload_question'
  post '/profiles/:id', to: 'profiles#update'
  resources :profiles

  
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :results, dependent: :destroy
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]
  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
    render layout: 'admin'

  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new

    @subject = Subject.new
    render layout: 'admin'

  end

  # GET /subjects/1/edit
  def edit
    render layout: 'admin'

  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        upload_question(params,@subject.id)
        format.html { redirect_to root_path, notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        upload_question(params,@subject.id)
        format.html { redirect_to root_path, notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name, :duration)
    end






    def upload_question(params,subject_id)
      file = params[:subject][:upload_file].tempfile
      all_question=[]
      option_value=[]
  
      answer_keys=["a"=>0,"b"=>1,"c"=>2,"d"=>3,"e"=>4,"f"=>5]
      index=-1
      option_no=1
      data=File.foreach(file).map { |line|
        if line.include? "QUES"
          option_no=1
          option_value=[]
          index=index+1
          all_question[index]={}
          all_question[index]['subject_id']=subject_id
        line= line.split('.')
          all_question[index]['question']=line[1].gsub(/\s+/, ' ')
        else
          if line.include? "("
            if line.include? "उत्तर"
              key=line.gsub(/\s+/, ' ').gsub('(','').gsub(')','').split('-').last.strip
              all_question[index]["correct_answer"]= option_value[answer_keys[0]["#{key}"]]
              option_no= option_no+1
            else
              option_value << line.gsub(/\s+/, ' ').split(')').last.strip
              all_question[index]["options"]=option_value
              option_no= option_no+1
            end
          end
        end  
      }  
  
      questions=Question.import all_question
      # redirect_to , notice: "Questions Created Successfully"
    end


end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, class: "contents") do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :duration %>
    <%= form.number_field :duration, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <div style="color:red;font-size:15px">**if time quiz**</div>
  </div>
  <div class="my-5">
    <%= form.label :upload_file %>
    <%= form.file_field :upload_file,id: "question-file", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "submit-button rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer",type:"button" %>
  </div>
<% end %>
<script>
  $("#question-file").on("change",function () {
    $(".submit-button").attr("type","submit");
  })
</script>

app/views/subjects/_subject.html.erb
          <tr class="bg-white">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= subject.name %></td>
              <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
               <%= link_to 'Edit this subject', edit_subject_path(subject), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
              </td>
            </tr>

app/views/subjects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing subject</h1>

  <%= render "form", subject: @subject %>

  <%= link_to "Show this subject", @subject, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to subjects", subjects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subjects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-6 ">
    <h1 class="font-bold text-4xl">Subjects</h1>
    
    <%= link_to 'New subject', new_subject_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>



<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody>
               <%= render @subjects %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</div>

app/views/subjects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New subject</h1>

  <%= render "form", subject: @subject %>

  <%= link_to 'Back to subjects', subjects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subjects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @subject %>

    <%= link_to 'Edit this subject', edit_subject_path(@subject), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this subject', subject_path(@subject), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to subjects', subjects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>