config/routes.rb
Rails.application.routes.draw do
  resources :file_upload_questions
  resources :results
  resources :questions
  get 'select_quiz_type', to: 'questions#select_quiz_type'
  get 'quiz_questions',to: 'questions#quiz_questions'
  resources :quizzes
  resources :subjects
  post 'upload_question', to: 'questions#upload_question'

  # resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
    post 'sign_up_with_credentials',to: 'admins/sessions#sign_up_with_credentials'
    post 'sign_in_with_credentials', to: 'admins/sessions#sign_in_with_credentials'
    post 'register', to: 'admins/sessions#register'
  end


  post 'test_result',to: 'questions#test_result'
  post 'upload_question',to: 'questions#upload_question'
  post '/profiles/:id', to: 'profiles#update'
  resources :profiles

  
end

app/views/layouts/_nav_bar.html.erb
<!-- Navbar -->
<nav class="flex-shrink-0 bg-white shadow-xl">
    <div class="max-w-7xl mx-auto px-2 sm:px-4 lg:px-8">
        <div class="relative flex items-center justify-between h-16">
        <!-- Logo section -->
        <div class="flex items-center px-2 lg:px-0 xl:w-64">
            <div class="flex-shrink-0">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-300.svg" alt="Workflow">
            </div>
        </div>

        
        <div class="flex lg:hidden">
            <!-- Mobile menu button -->
            <button type="button" class="bg-indigo-600 inline-flex items-center justify-center p-2 rounded-md text-indigo-400 hover:text-white hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            
            <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
            </svg>
            
            <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
            </button>
        </div>
        <!-- Links section -->
        <div class="hidden lg:block lg:w-auto">
            <div class="flex items-center justify-end">
            <div class="flex">
            <% Subject.all.each do |subject| %>

                <a href="<%= questions_path(id:subject.id) %>" class=" text-gray-700  hover:text-gray-900 hover:bg-gray-100 block px-3 py-2 rounded-md text-base font-medium"><%= subject.name %></a>

                <% end %>

    </div>
            <!-- Profile dropdown -->
            <div class="ml-4 relative flex-shrink-0">
                <div>
                <button type="button" class="profile_icon bg-indigo-700 flex text-sm rounded-full text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-indigo-700 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                    <span class="sr-only">Open user menu</span>
                    <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=256&h=256&q=80" alt="">
                </button>
                </div>

                <div class="profile_menu z-10 origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                <!-- Active: "bg-gray-100", Not Active: "" -->
                <a href="<%= profile_path(current_admin) %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>

                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                
                <a href="<%= destroy_admin_session_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="lg:hidden" id="mobile-menu">
        <div class="px-2 pt-2 pb-3 space-y-1">
        <a href="#" class="text-white bg-indigo-800 block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Hindi</a>

        <a href="#" class="text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600 block px-3 py-2 rounded-md text-base font-medium">English</a>

        <a href="#" class="text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600 block px-3 py-2 rounded-md text-base font-medium">Math</a>

        <a href="#" class="text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600 block px-3 py-2 rounded-md text-base font-medium">Science</a>

        <a href="#" class="text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600 block px-3 py-2 rounded-md text-base font-medium">Social science</a>

        </div>
        <div class="pt-4 pb-3 border-t border-indigo-800">
        <div class="px-2 space-y-1">
            <a href="<%= profile_path(current_admin) %>" class="block px-3 py-2 rounded-md text-base font-medium text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600">Your Profile</a>

            <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600">Settings</a>

            <a href="<%= destroy_admin_session_path %>" class="block px-3 py-2 rounded-md text-base font-medium text-indigo-200 hover:text-indigo-100 hover:bg-indigo-600">Sign out</a>
        </div>
        </div>
    </div>
</nav>

app/views/layouts/admin.html.erb
  <html class="h-full">
  <head>
    <title>GoogleOauthDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
  <!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-white shadow">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button -->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
         
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <img class="block lg:hidden h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
          <img class="hidden lg:block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-800-text.svg" alt="Workflow">
        </div>
        <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
          <a href="#" class="border-indigo-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"> Dashboard </a>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
       
        <div class="ml-3 relative">
          <div>
            <button type="button" class="profile_icon bg-white rounded-full flex text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>
          <div class="profile_menu origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile : <%= current_admin.email %> </a>
            <a href="<%= destroy_admin_session_path %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
              </div>   
         </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="pt-2 pb-4 space-y-1">
      <a href="#" class="bg-indigo-50 border-indigo-500 text-indigo-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium">Dashboard</a>
    </div>
  </div>
</nav>
   <main class="container mx-auto px-5 flex">
      <%= yield %>
    </main>

  </body>

  <script>
  $(document).ready(function(){
    $(".profile_menu").toggle();
    $(".profile_icon").click(function(){
      $(".profile_menu").toggle();
    });
  });

  </script>
</html>

app/views/layouts/application.html.erb
  <html class="h-full">
  <head>
    <title>GoogleOauthDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body class="bg-gray-100"">
    <main class="container mx-auto px-5 flex bg-gray-100"> 

      <%= yield %>
    </main>
    
  </body>
</html>

app/views/layouts/dashboaard.html.erb
  <html class="h-full">
  <head>
    <title>GoogleOauthDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body class="bg-color-100">
<div class="relative min-h-full flex flex-col mt-0">
  <%= render 'layouts/nav_bar'%>
  <%= yield %>
    
</div>

  </body>

  <script>
  $(document).ready(function(){
    $(".profile_menu").toggle();

    $(".profile_icon").click(function(){
      $(".profile_menu").toggle();
    });
  });

  </script>
</html>

app/views/layouts/student_index.html.erb
<html class="h-full">
  <head>
    <title>GoogleOauthDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <style>
        .flash__alert   { color: red; }
        .flash__notice  { color: blue; }
        .flash__success { color: green; }
    </style>
  </head>

  <body>
    <div style="height:100vh;z-index:100;background-image:linear-gradient(to bottom right, rgba(47, 69, 168, 0.8), rgba(190, 71, 181, 0.8)),url(<%= image_url("homepage_background.jpeg") %>);background-size: 100vw 100vh;">
        <div class="mx-auto mt-8 mx:auto w-full text-center inline-block ">
          <ul class="flex justify-center space-x-4">
            <li class="float-left text-white">
              <a class="text-white text-lg" style="color:white" href="#" >Demos </a>
            </li>
            <li class="float-left text-white ">
              <a class="text-white text-lg" style="color:white" href="#">Featured</a>
            </li>
            <li class="float-left text-white ">
              <a class="text-white text-lg" style="color:white" href="#">Pages</a>
            </li>
            <li class="float-left text-white ">
              <a class="text-white text-lg" style="color:white" href="#">Elements</a>
            </li><li class="float-left text-white">
              <a class="text-white text-lg" style="color:white" href="#">Portfolio</a>
            </li><li class="float-left text-white ">
              <a class="text-white text-lg" style="color:white" href="#">Blog</a>
            </li>
          </ul>  
        <div class="float-right text-white mr-5" style="margin-top:-25px">
              <a href="<%= destroy_admin_session_path %>"class="hover:text-xl text-white text-lg float-right" style="color:white">Sign Out</a>
        </div>       
        </div>
        <%= yield %>
    </div>    
  </body>
</html>
<style>
a:link,
    a:visited {
      text-decoration:none;
      background: transparent;
    }
ul a:hover{
  color: white !important;
}

li > a:after{
    content: '';
    display: block;
    height: 1.5px;
    background: white;
    transform: scaleX(0);
    transition: transform .3s;
}
li > a:hover:after{
    transform: scaleX(1);
    transition: transform .3s;
}
</style>